name: Run Full Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Node.js dependencies
        run: npm install
        working-directory: ui-tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ui-tests
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Start local HTTP server
        run: |
          python -m http.server 8000 &
          sleep 5
          curl --retry 10 --retry-connrefused --retry-delay 2 http://localhost:8000/demo.html
      - name: Run Playwright tests
        run: npx playwright test --timeout=30000 || true
        working-directory: ui-tests
      - name: Run Python tests
        run: pytest --junitxml=python-test-results.xml || true
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
      - name: Upload Python test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-test-report
          path: .pytest_cache/
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: python-test-results.xml 